import { Box, Heading } from '@chakra-ui/layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfileCard from '../components/ProfileCard'

const About = () => (
  <Box paddingX={{ lg: 52, base: 4 }}>
    <Head>
      <title>TCon</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Heading
      as="h1"
      size={'2xl'}
      color="#748A9D"
      textAlign="center"
      marginY="12"
    >
      About Us
    </Heading>
    <p color="#605C5C">
      TCon is an application for those who need technological solutions for
      their specific problems. This application allows users to consult
      technology experts directly to solve user problems.
    </p>
    <Box
      display="flex"
      justifyContent="center"
      alignItems="center"
      marginY="16"
    >
      <Image
        src="/images/logopanjang.png"
        alt="logo"
        width={500}
        height={250}
      />
    </Box>
    <p color="#605C5C">
      Tcon aims to help potential problems that will arise in industry 4.0,
      namely:
    </p>
    <ol type="1">
      <Box paddingLeft="16px">
        <li>Bringing convenience to consulting in the IT field</li>
        <li>
          Supporting the community to be more advanced and able to follow the
          flow of technological developments
        </li>
        <li>
          It bridges and allows the user to consult on the technology exerts
          without having to make a lot of time and money.
        </li>
      </Box>
    </ol>
    <Heading
      as="h1"
      size={'2xl'}
      color="#748A9D"
      textAlign="center"
      marginTop="32"
      marginBottom="12"
    >
      Know More About Our Team
    </Heading>
    <Box
      display="flex"
      justifyContent="space-around"
      alignItems="center"
      flexWrap="wrap"
    >
      <ProfileCard name="Cornelius Tantius" />
      <ProfileCard name="Ricky" />
      <ProfileCard name="Brian Karnadi Japar" />
      <ProfileCard name="Jonathan Kristianto" />
      <ProfileCard name="Raymond Tiandinatan" />
    </Box>
    <Box>
      <Heading
        as="h1"
        size={'2xl'}
        color="#748A9D"
        textAlign="center"
        marginTop="32"
        marginBottom="12"
      >
        Contact Us
      </Heading>
      <p>
        Do you have problems with our application. Dont understand how to use
        it, or have criticism or suggestions for our Application To be able to
        develop more?
      </p>
      <Box display="flex" alignItems="center" marginTop="20px">
        <Image
          src="/images/about/home.svg"
          width="50"
          height="50"
          alt="home icon"
        />
        <Heading
          size={'lg'}
          color="#748A9D"
          textAlign="center"
          marginLeft="20px"
        >
          Jakarta, DKI 1234, Indonesia
        </Heading>
      </Box>
      <Box display="flex" alignItems="center" marginTop="20px">
        <Image
          src="/images/about/email.svg"
          width="50"
          height="50"
          alt="email icon"
        />
        <Heading
          size={'lg'}
          color="#748A9D"
          textAlign="center"
          marginLeft="20px"
        >
          apptcon@gmail.com
        </Heading>
      </Box>
      <Box display="flex" alignItems="center" marginTop="20px">
        <Image
          src="/images/about/home.svg"
          width="50"
          height="50"
          alt="about icon"
        />
        <Heading
          size={'lg'}
          color="#748A9D"
          textAlign="center"
          marginLeft="20px"
        >
          +62 812 3456 789
        </Heading>
      </Box>
    </Box>
    <Box marginY="24px">Feel Free to Contact Us ^^</Box>
  </Box>
)

export default About
