/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import {
	FormLabel,
	Flex,
	Input,
	Stack,
	FormControl,
	Box,
	Button,
	Text,
} from "@chakra-ui/react";
import Image from "next/image";
import Logo from "../assets/logoTCon.png";
import { useState } from "react";

export default function Login() {
	const [email, setEmail] = useState();
	const [password, setPassword] = useState();

	const handleSubmit = (e) => {
		e.preventDefault();
		console.log(email, password);
	};

	return (
		<div>
			<Head>
				<title>Sign In</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box>
				<Stack
					id="about"
					align="center"
					minH={"100vh - "}
					direction={{ base: "column-reverse", md: "row" }}
					px={{ base: "0", md: "48" }}
				>
					<Flex flex={1}>
						<Box
							w={{ base: "320px", lg: "500px" }}
							h={{ base: "320px", lg: "500px" }}
						>
							<Box
								alignItems="center"
								d="flex"
								flexDir="column"
								justifyContent="center"
								h="full"
								my="auto"
								position="relative"
							>
								<Image
									alt={"Login Image"}
									objectFit={"cover"}
									src={Logo}
									objectPosition="center"
								/>
								<Text fontSize="md" color="#7e7e7e">
									Ready To Consul?
								</Text>
							</Box>
						</Box>
					</Flex>
					<Flex p={8} flex={1} align={"center"} justify={"center"}>
						<Stack spacing={6} w={"full"} maxW={"lg"}>
							<Box
								bg="#e2e2e2"
								w="full"
								h="full"
								rounded="2xl"
								px="20px"
								py="44px"
							>
								<form onSubmit={handleSubmit}>
									<FormControl id="first-name" isRequired>
										<FormLabel>Email</FormLabel>
										<Input
											placeholder="Email"
											bg="white"
											onChange={(e) => setEmail(e.target.value)}
										/>
									</FormControl>
									<FormControl id="first-name" isRequired>
										<FormLabel>Password</FormLabel>
										<Input
											placeholder="Password"
											type="password"
											bg="white"
											onChange={(e) => setPassword(e.target.value)}
										/>
									</FormControl>
									<Box pt="20px">
										<Button type="submit">Sign In</Button>
										<Box d="flex" pt="2">
											<Text fontSize="md">Dont have an account?</Text>
											<Text
												as="a"
												cursor="pointer"
												fontSize="md"
												fontWeight="bold"
												color="#52C8FA"
											>
												&nbsp; Sign Up
											</Text>
										</Box>
									</Box>
								</form>
							</Box>
						</Stack>
					</Flex>
				</Stack>
			</Box>
		</div>
	);
}
