import Head from "next/head";
import { Box, SimpleGrid, Text, useBreakpointValue } from "@chakra-ui/react";
import React, { useState } from "react";
import axios from "axios";
import Card from "../components/Card";
import { useRouter } from "next/router";

export interface Consultant {
	email: string;
	name: string;
	phone: string;
	userId: string;
}

interface SearchProps {
	data: {
		consultants: Consultant[];
	};
}
export default function Search({ data }: SearchProps) {
	const router = useRouter();
	const responsive = useBreakpointValue({ base: 1, md: 3 });

	return (
		<>
			<Head>
				<title>Search: {router.query.c}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/tconnotext.png" />
			</Head>
			<Box p={{ base: "10", md: "20" }} pt={{ base: "5", md: "5" }}>
				<Text fontWeight="bold" fontSize="xl" py="2" color="gray.700">
					Search result for: {router.query.c}
				</Text>
				<SimpleGrid columns={responsive} spacing={8}>
					{data.consultants
						.filter((data) =>
							data.name.toLowerCase().includes(router.query.c as string)
						)
						.map((c) => (
							<Card key={c.userId} consultant={c} />
						))}
				</SimpleGrid>
			</Box>
		</>
	);
}

export async function getServerSideProps() {
	try {
		const res = await axios.get(
			"https://tcon-api.herokuapp.com/consultant/getall"
		);
		return {
			props: {
				data: res.data,
			},
		};
	} catch (err) {
		console.log(err);
	}
}
